urdf_parser/src/link.cpp, urdf_parser/src/model.cpp, urdf_parser/src/urdf_model_state.cpp, urdf_parser/src/urdf_sensor.cpp, urdf_parser/src/world.cpp
Make sure functions have something to return, and reduce warnings about unused catch variables.
See also https://github.com/ros/urdfdom_headers/pull/10
@nkoenig
=> Fixes from sdformat

urdf_parser_py/src/urdf_parser_py/urdf.py
The current urdf.py gives an unnecessary error when parsing latest URDF format transmission (http://wiki.ros.org/urdf/XML/Transmission). New format requires that hardwareInterface is defined in transmission joints.
This pull makes hardwareInterface optional in both joint and actuator which stop unwanted errors.
=> made hardware interface optional in both transmission actuator and joint

CMakeLists.txt, urdf_parser/include/urdf_parser/urdf_parser.h, urdf_parser/src/check_urdf.cpp, urdf_parser/src/link.cpp, urdf_parser/src/model.cpp, urdf_parser/src/urdf_model_state.cpp, urdf_parser/src/urdf_sensor.cpp, urdf_parser/src/urdf_to_graphiz.cpp
This uses the new pointer typedefs to aid in eventual migration away from boost smart pointers. It also uses the `urdf::dynamic_pointer_cast` function to aid in migration.
In order to use the new typedefs, we must find at least version 0.4 of `urdfdom_headers` (see https://github.com/ros/urdfdom_headers/pull/17 ), so we bump this version to 0.4 as well.
=> Use new pointer typedefs, bump to 0.4

urdf_parser/test/urdf_unit_test.cpp
One testcase added to highlight https://github.com/ros/urdfdom_headers/issues/18
Furthermore, a vast range of rpy test cases (obtained
as the permutation of given list of angles) was added to
make sure that they are all handled properly.
By the way, why this test was added in this repository @vrabaud ? 
It is only testing code that is contained in the urdfdom_headers repo.
=> [test] add extended tests for pose::get/setRPY

urdf_parser_py/CMakeLists.txt, urdf_parser_py/src/urdf_parser_py/urdf.py, urdf_parser_py/test/test_urdf.py, urdf_parser_py/test/xml_matching.py
The new transmission parser of `urdf_parser_py` didn't match the specification in the [wiki](http://wiki.ros.org/urdf/XML/Transmission#A.3Ctransmission.3E_Elements).
Moved `hardwareInterface` from `<actuator>` to `<joint>` and made them an aggregate (one to many such elements are possible according to specification).
=> fixed transmission parser to match specification

urdf_parser/src/link.cpp
The return signature of `parseLink` is bool, but the control flow of the function could reach the end of the function without returning bool.
This was causing a segfault in `urdf_parser` when I built it from source.
=> Add missing return statement

CMakeLists.txt, urdf_parser/src/joint.cpp, urdf_parser/src/link.cpp, urdf_parser/src/model.cpp, urdf_parser/src/pose.cpp, urdf_parser/src/twist.cpp, urdf_parser/src/urdf_model_state.cpp, urdf_parser/src/urdf_sensor.cpp
Require the latest version of console_bridge and use the new namespaced macros to prevent deprecation warnings.
=> Use console_bridge 0.3

.travis.yml, .travis/build
install libboost-test-dev, python-yaml
install to /usr with sudo
make test with verbose
language generic to fix python
@tfoote can you enable travis for this repository
It's [passing on my fork](https://travis-ci.org/scpeters/urdfdom/builds/103487994)
=> Update travis CI scripts

urdf_parser/include/urdf_parser/exportdecl.h
Bad copy and paste led to `console_bridge_EXPORTS` being used instead of `URDFDOM_EXPORTS` but it is fixed here. This was mentioned in #64.
=> urdf_parser: fix dll macro

.travis.yml, urdf_parser_py/src/urdf_parser_py/urdf.py, urdf_parser_py/test/test_urdf.py
According to http://wiki.ros.org/urdf/XML/link#line-79, a material of a link can be referenced only by name. But if neither a color tag nor a texture tag is present within a material tag, "Material has neither a color nor texture" error occurs.
This PR suppresses the above error.
=> Color and texture in link material are optional

CMakeLists.txt
Remove a previous hack that set the library path to /usr. Delegate the path to `${CMAKE_INSTALL_FULL_LIBDIR}` which should know where to put it in the different distributions.
=> Install cmake modules into arch dependent path

urdf_parser/test/CMakeLists.txt, urdf_parser/test/urdf_double_convert.cpp
Note that this only tests that some simple cases do the correct
thing.  We can't reliably check the locale fixing
code because we can't depend on any particular locales being
installed on test machines.
This depends on https://github.com/ros/urdfdom_headers/pull/42, so should not be merged until that one is.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
=> Add in some tests for the strToDouble conversion.

urdf_parser/src/joint.cpp, urdf_parser/src/link.cpp, urdf_parser/src/urdf_model_state.cpp, urdf_parser/src/urdf_sensor.cpp, urdf_parser/test/urdf_unit_test.cpp
The short of it is that `str::stod` is not locale-safe, so instead we use the stream operator imbued as "classic" (C) locale.  This PR depends on https://github.com/ros/urdfdom_headers/pull/42, so it should not be merged until that one is merged/released.  While I was at it, I added a bunch of tests just to ensure we are doing the right thing in various places, mostly surrounding the conversion of strings to doubles.
=> Switch all stod callers in urdfdom to use a helper

urdf_parser/test/CMakeLists.txt
Fixes ros2/urdfdom#10.
The warning in the packaging job is gone: https://ci.ros2.org/job/ci_packaging_osx/31/consoleFull#console-section-21
And the normal CI build still passes the tests: https://ci.ros2.org/job/ci_osx/3543/consoleFull#console-section-23
=> remove invalid link dir

.travis/build, urdf_parser/test/CMakeLists.txt, urdf_parser/test/urdf_unit_test.cpp
This PR adds a test for color parsing. To check locale dependent issues it adds the Dutch locale to the travis environment and then runs tests both with LC_ALL=C and LC_ALL=nl_NL.UTF-8
With the current version of urdfdom_headers this is expected to fail for Dutch but not for "Classic". https://github.com/ros/urdfdom_headers/pull/47 should fix it for Dutch (and other European languages)
Please squash on merge
=> Test locale

urdf_parser/include/urdf_parser/urdf_parser.h, urdf_parser/src/model.cpp, urdf_parser/test/CMakeLists.txt, urdf_parser/test/urdf_version_test.cpp
This is already specified by the xsd, so just make sure we
implement it and enforce it in the code.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
@sloretz @scpeters FYI
=> Add in support for a version tag.

urdf_parser/test/urdf_unit_test.cpp
There is currently no explicit test for correct float parsing for eg `xyz` vectors
Please feel relieved that I did not find a new regression, just making checks more explicit in light of the discussion on https://github.com/ros/urdfdom/issues/119
=> add an explicit float check

CMakeLists.txt
We just released console_bridge 1.0, but urdfdom fails to find it when searching for version `0.3`. This searches for 1.0 if 0.3 is not found.
First noticed the failure in https://github.com/Homebrew/homebrew-core/pull/55355
=> Find console_bridge without explicit version

urdf_parser/src/urdf_to_graphiz.cpp
Currently `urdf_to_graphiz` writes the pdf to `$ROBOT_NAME.gv`/`$ROBOT_NAME.pdf` in the current working directory. This is problematic especially when using this in scripts, as one would either have to read the XML-file to know where this file was saved or  to read the stdout of `urdf_to_graphiz`
Moreover, it seems more handy to put the pdf in the same directory as the urdf. This way you can find it really easier later on and you don't have to move it to the urdf. Also when there might exist multiple URDFs for the same robot (same robot name) this prevents overwriting of files.
This MR saves the files right beneath the urdf by just appending `.gv` or `.pdf` to the input path.
=> Change output file of urdf_to_graphiz

CMakeLists.txt, cmake/urdfdom-config.cmake.in
If MSVC is not set CMAKE_DEBUG_POSTFIX is empty and the generated
urdfdom-config.cmake finds the normal library as debug library and
generates wrong $<$<CONFIG:Debug>: prefixes.
CMAKE_DEBUG_POSTFIX is only used in urdfdom-config.cmake.in so this
patch removes it completely.
=> Fix cmake if not compiled with MSVC

package.xml
Gtest `internal-utils.cmake` script [uses the Python3 interpreter](https://github.com/ros/urdfdom/blob/99ec1f99f2d175f07cc26e63082502ee62982dac/urdf_parser/test/gtest/cmake/internal_utils.cmake#L249) however it is not installed by rosdep (on systems that does not ship it by default).
Note that the issue was spotted from the `foxy` branch hence this will require backport.
=> Fix missing test_depend on python3

urdf_parser/src/check_urdf.cpp, urdf_parser/src/link.cpp, urdf_parser/src/model.cpp, urdf_parser/src/urdf_to_graphviz.cpp
For non-primitive types, using prefix ++/-- operator is faster.
And two not necessary if condition are removed.
=> refactor: Improve performance

urdf_parser/src/check_urdf.cpp
Makes it easier to pipe results from xacro, and matches urdfdom_py's behavior
Switch an fstream to an ifstream for clarity
Closes #170
=> Support checking a URDF given on stdin

CMakeLists.txt, urdf_parser/CMakeLists.txt, urdf_parser/include/urdf_parser/urdf_parser.h, urdf_parser/src/check_urdf.cpp, urdf_parser/src/model.cpp
That way, we don't have to export the tinyxml2 dependencies to downstream consumers.  It is just a private dependency at that point.
Based on the code in https://github.com/SMillerDev/urdfdom/commit/092b57c20bca37d1d81eaa6da6b08a7bebb04662
Closes #189
@scpeters @sloretz Thoughts from both of you appreciated.
@traversaro If you have time, any testing you can do on this is highly appreciated.
=> Remove tinyxml2 from public dependencies.

CMakeLists.txt, urdf_parser/CMakeLists.txt
The overall rationale is, that the current behavior is not well suited for cross-compiling or relocation of the package. This
commit shall address some of the issues found. 
There are some absolute path in the generation of the .cmake files which ruin the creation of relocatable packages.
Fixing:
* CMAKE_MODULE_PATH append instead of replacement
* Do not expose TinyXML Path (private instead of public)
* INTERFACE use relative path instead of ${CMAKE_INSTALL_INCLUDEDIR}
See also
https://cmake.org/cmake/help/latest/guide/importing-exporting/index.html#creating-relocatable-packages
for reference.
Signed-off-by: Matthias Schoepfer <m.schoepfer@rethinkrobotics.com>
=> CMakeLists.txt: Some fixes for Relocatable package

urdf_parser/include/urdf_parser/urdf_parser.h, urdf_parser/src/joint.cpp, urdf_parser/src/link.cpp, urdf_parser/src/model.cpp, urdf_parser/src/pose.cpp, urdf_parser/src/pose.hpp, urdf_parser/src/urdf_sensor.cpp
In an earlier commit, we changed from tinyxml -> tinyxml2 in the public API because we thought that there were no users of these APIs.  Codify that here by marking these APIs as deprecated; if a user comes along and says that they are actually using it, we can undeprecated it.
Note that in order to avoid deprecations from within the library, I had to add a bit of additional indirection here. If we remove the APIs in the future, we can also remove this indirection.
@scpeters @sloretz FYI.
=> Deprecate the APIs that we think are unused.

urdf_parser/CMakeLists.txt
Fix https://github.com/ros/urdfdom/issues/203 . This ensure that the library can also be used easily via CMake's FetchContent in a way consistent with using the library via `find_package(urdfdom)` , see https://github.com/ament/ament_cmake/issues/351 for some reference on this.
=> Add ALIAS targets for urdfdom libraries
